pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Aplomb & The Creative Conspiracy
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://aplombclothing.com/
#
# 2. URL of this page
url:              http://nickychulo.github.io/kicklandz/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           Aplomb & The Creative Conspiracy
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://kck.st/1f1gNHu
  #
  # URL of a cover photo of your project
  cover_image:    http://aplombclothing.com/wp-content/uploads/2013/08/kicker.jpg
  #
  # Use a one-liner to describe your project
  description:    An apparel brand with its own creative community. The Creative Conspiracy supplies the concept, we design it.
#
# 4. Your Twitter handle
twitter_handle:   AplombandTCC
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  We sincerely appreciate your assistance in spreading the word about us. One day we'll<br />
  tell our Grandchildren about you!<br />
